version: "3.7"
services:
  # backend:
  #   container_name: api
  #   restart: always
  #   build: .
  #   ports:
  #     - "4000:4000"
    # links:
    #   - mongodb
  mongoDb:
    container_name: mongoDb
    image: mongo:3.6.19
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
